### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by smelfungus** [side-codes/anyColorPicker#49]
## :rocket: Roadmap

- [ ] Add more picker types
    - [x] HLS SeekBars
    - [x] RGB SeekBars
    - [ ] RGB circle
    - [ ] RGB plane
    - [ ] HSV/HSB seekbars
    - [x] CMYK SeekBars
    - [x] Alpha SeekBars
    - [ ] HSL (S+L) plane
    - [ ] LAB
    - [ ] XYZ
    - [ ] YPbPr
    - [x] Swatches
- [ ] Extend picker types
    - [ ] CMYK SeekBars coloring modes
    - [ ] More awesome swatches
    - [ ] More supported alpha color models
- [x] Sample buttons -> radios
- [x] Remove sample app child press delays
- [x] Enhance API
- [x] Add XML attributes
- [x] Provide *git-flow*
- [ ] Automate release/publish flow
- [x] Add thumb animation
- [x] Add *MaterialDrawer* & sample fragments
- [x] Add more *HSLColorPickerSeekBar* checks and reduce calls count
- [x] Add more encapsulation to limit picker modification capabilities
- [x] Package repository publish *(Bintray)*
- [ ] Add *Rx* support
- [x] Add/Revisit *RecyclerView* support
- [x] Add sample app icon
- [ ] Add logger solution
- [ ] Add sample app analytics
- [ ] Add GIFs media
- [ ] Add call flow diagram
- [ ] Add tests
- [ ] Add docs
- [ ] Add contribution guidelines
- [x] Add OSS licenses
- [x] Add license
